baseURL = "https://portfoliofestiandrea.netlify.app"
languageCode = "en-us"
theme = "apsho"
title = "Andrea Festi | Sito ufficiali di Andrea Festi"
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[[menu.main]]
name = "PROGETTI"
url = "#faq"
weight = 3
[[menu.main]]
name = "About"
url = "/blog/about"
weight = 2
[[menu.main]]
name = "Home"
url = "#hero"
weight = 1
[[menu.sitemap]]
name = "Contact"
url = "/contact"
weight = 4
[[menu.sitemap]]
name = "Privacy & Policy"
url = "/privacy"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "/blog"
weight = 2
[[menu.sitemap]]
name = "Home"
url = "#"
weight = 1
[params]
copyright1 = "All right reserved"
copyright2 = "Copyright Â©  <a href=\"https://www.linkedin.com/in/andreafesti\" target=\"_blank\">Andrea Festi </a> {year}"
email = "festi.andrea@gmail.com"
fabFormURL = "https://fabform.io/f/zWMBVeW"
footerTitle = "Rimaniano in contatto"
googleAnalytics = "UA-175025671-2"
logo = "images/logo.svg"
[params.address]
address = "Rovereto (TN), Italia"
email = "festi.andrea@gmail.com"
phone = "340 87 28 017"
[params.social]
facebook = "https://www.facebook.com/festi.andrea95"
instagram = "https://www.instagram.com/andrea_festi"
linkedin = "https://www.linkedin.com/in/andreafesti"
youtube = "https://www.youtube.com/c/AndreaFesti"
